### ISSUE TITLE
No icon when installed (Ubuntu 23.04)

### ISSUE THREAD

**Issue by AnnualPath** [JitPatro/CyberChef-Snap#1]
I downloaded this app off the Snap store and was unable to find the icon to launch the app. I am using Ubuntu 23.04 stock GNOME.

Thanks

**Comment by JitPatro** [comment]
Hi @AnnualPath, thanks for reporting this issue. I just added the desktop menu icon. Can you refresh the `cyberchef` snap from the edge channel, with `snap refresh cyberchef --edge` command from a terminal? Let me know how it goes.
